version: '3'

services:
  app:
    container_name: unixify-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=unixify
      - DB_SSLMODE=disable
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - unixify-network

  db:
    container_name: unixify-db
    image: docker.io/library/postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=unixify
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - unixify-network

volumes:
  postgres_data:

networks:
  unixify-network:
    name: unixify-network